// Mocks generated by Mockito 5.4.4 from annotations
// in gongbab/test/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:gongbab/data/auth/auth_token_manager.dart' as _i3;
import 'package:gongbab/data/device/device_info_service.dart' as _i10;
import 'package:gongbab/domain/entities/auth/login_entity.dart' as _i7;
import 'package:gongbab/domain/repositories/auth_repository.dart' as _i2;
import 'package:gongbab/domain/usecases/login_usecase.dart' as _i4;
import 'package:gongbab/domain/utils/result.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthTokenManager_1 extends _i1.SmartFake
    implements _i3.AuthTokenManager {
  _FakeAuthTokenManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i4.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AuthRepository);

  @override
  _i3.AuthTokenManager get authTokenManager => (super.noSuchMethod(
        Invocation.getter(#authTokenManager),
        returnValue: _FakeAuthTokenManager_1(
          this,
          Invocation.getter(#authTokenManager),
        ),
      ) as _i3.AuthTokenManager);

  @override
  _i5.Future<_i6.Result<_i7.LoginEntity>> execute({
    required String? code,
    required String? deviceType,
    required String? deviceId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #code: code,
            #deviceType: deviceType,
            #deviceId: deviceId,
          },
        ),
        returnValue: _i5.Future<_i6.Result<_i7.LoginEntity>>.value(
            _i8.dummyValue<_i6.Result<_i7.LoginEntity>>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #code: code,
              #deviceType: deviceType,
              #deviceId: deviceId,
            },
          ),
        )),
      ) as _i5.Future<_i6.Result<_i7.LoginEntity>>);
}

/// A class which mocks [AuthTokenManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthTokenManager extends _i1.Mock implements _i3.AuthTokenManager {
  MockAuthTokenManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> saveTokens(
    String? accessToken,
    String? refreshToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTokens,
          [
            accessToken,
            refreshToken,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveRestaurantInfo(
    int? restaurantId,
    String? kioskCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRestaurantInfo,
          [
            restaurantId,
            kioskCode,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DeviceInfoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoService extends _i1.Mock implements _i10.DeviceInfoService {
  MockDeviceInfoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> getDeviceId() => (super.noSuchMethod(
        Invocation.method(
          #getDeviceId,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getDeviceId,
            [],
          ),
        )),
      ) as _i5.Future<String>);
}
